fix #151 handle multiple wallets same currency
bitcartcc/bitcart pull request #155
Opened 2021-01-09 21:19 UTC by xiaoxianma

enhance logging of creating payment methods

2021-01-17 19:28 UTC, MrNaif2018 commented on api/crud.py
> +            f"Payment method(wallet_id={wallet_id}),store={store.id},currency={wallet.currency} is added to invoice {invoice.id}"
```suggestion
            f"Payment method(wallet={wallet_id}, store={store.id}, currency={wallet.currency}) is added to invoice {invoice.id}"
```

2021-01-17 19:38 UTC, MrNaif2018 requested changes
Thank you for your PR! Please take a look at review comments

2021-01-17 19:38 UTC, MrNaif2018 commented on api/crud.py
> +            f"Payment method(wallet_id={wallet_id}),store={store.id},currency={wallet.currency} is added to invoice {invoice.id}"
```suggestion
            f"Payment method(wallet={wallet_id}, store={store.id}, currency={wallet.currency}) is added to invoice {invoice.id}"
```

2021-01-17 19:38 UTC, MrNaif2018 commented on api/crud.py
> -        # TODO remove duplication
By remove duplication I meant, see the `_create_payment_method` method, it contains the same code but misses name attribute.
Please fix this, maybe we can make a class method `format` or `json` (probably the latter) that will return json representation of a model. In general I think in the future we will need to abstract this more

2021-01-17 19:38 UTC, MrNaif2018 commented on api/crud.py
> +            name = method.currency if len(methods) == 1 else f"{currency} ({i})"
I think we can apply all the formatting the frontend does right there, as name is no longer used as dictionary key.
if it is lightning and there are multiple currencies, it should look like so:
BTC (⚡) (1)
BTC (⚡) (2)

Or do you have any better ideas?

2021-01-18 00:29 UTC, xiaoxianma commented on api/models.py
> +    async def to_enhanced_dict(self):
cannot pick a good name

2021-01-19 19:44 UTC, MrNaif2018 commented
Retrigerring CI

2021-01-20 11:15 UTC, MrNaif2018 approved these changes
Thank you for your PR! Merging!

2021-01-20 11:15 UTC, merged